version: "3.1"

services:

  mongodb:
    image: mongo
    restart: always
    container_name: mongo
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: haruncan
      MONGO_INITDB_ROOT_PASSWORD: haruncanaa



  elasticsearch:
      image: elasticsearch:8.4.2
      ports:
        - '9200:9200'
        - '9300:9300'
      environment:
        - discovery.type=single-node
        - ES_JAVA_OPTS=-Xms750m -Xmx750m
        - xpack.security.enabled=false

  hc-s3:
    image: minio/minio:RELEASE.2021-02-11T08-23-43Z
    ports:
      - '9000:9000'
    environment:
      MINIO_ROOT_USER: HK-MINIO
      MINIO_ROOT_PASSWORD: HK-MINIO-PASS
    command: server /data


